languageCode:           "en"
title:                  "Bootstrap"
baseURL:                "https://getbootstrap.com"

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_site"

module:
  mounts:
    - source:           dist
      target:           static/docs/5.1/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/5.1/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/5.1/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "The most popular HTML, CSS, and JS library in the world."
  authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"
  social_image_path:    /docs/5.1/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/5.1/assets/brand/bootstrap-social-logo.png

  current_version:      "5.2.0-alpha1"
  current_ruby_version: "5.2.0-alpha1"
  docs_version:         "5.1"
  rfs_version:          "v9.0.6"
  github_org:           "https://github.com/twbs"
  repo:                 "https://github.com/twbs/bootstrap"
  twitter:              "getbootstrap"
  slack:                "https://bootstrap-slack.herokuapp.com/"
  opencollective:       "https://opencollective.com/bootstrap"
  blog:                 "https://blog.getbootstrap.com/"
  themes:               "https://themes.getbootstrap.com/"
  icons:                "https://icons.getbootstrap.com/"

  download:
    source:             "https://github.com/twbs/bootstrap/archive/v5.2.0-alpha1.zip"
    dist:               "https://github.com/twbs/bootstrap/releases/download/v5.2.0-alpha1/bootstrap-5.2.0-alpha1-dist.zip"
    dist_examples:      "https://github.com/twbs/bootstrap/releases/download/v5.2.0-alpha1/bootstrap-5.2.0-alpha1-examples.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-alpha1/dist/css/bootstrap.min.css"
    css_hash:         "sha384-jpSUJwRDuBwtPS1FShEE1jROtoemB+7mpGLYW9Vqn3tztkXAvw/fB50Us9jyFTbd"
    css_rtl:          "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-alpha1/dist/css/bootstrap.rtl.min.css"
    css_rtl_hash:     "sha384-8VTUo+mPRrhc9IqTJLRP6bwV/lRHqV+zuwlxTFLHrmy0HCHON0vKVbPfh1CHky/m"
    js:               "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-alpha1/dist/js/bootstrap.min.js"
    js_hash:          "sha384-b3I3Yq/9L7iADksu7MugHKGIjNoT+54y6IT+W4QPDKbYO8rWUccf/lJZVDRMBLPD"
    js_bundle:        "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-alpha1/dist/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-5J32HGwLVXY3VjxDUT/qzna21dr8cLMLYNZC9EmGan21ST9wVyu+MZVgpPXrwSpa"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.2/dist/umd/popper.min.js"
    popper_hash:      "sha384-q9CRHqZndzlxGLOj+xrdLDJa9ittGte1NksRmgJKeCV9DrM7Kz868XYqsKWPpAmn"
